### ISSUE TITLE
tesseract languages in papermerge-multilangocr don't install

### ISSUE THREAD

**Issue by grimpeur78** [linuxserver/docker-mods#162]
Hi guys,

Thanks for creating the papermerge-multilangocr mod, it's exactly what I need to process mainly non-english documents.

However, when starting the container, it seems that the tesseract-lang files are not getting installed. Trying to install language support for German, English and Spanish, the log reads:

```
papermerge       | 2021-01-12T08:36:39.420992960Z package tesseract-ocr-"deu not found in the repository, skipping
papermerge       | 2021-01-12T08:36:43.833110801Z installing tesseract-ocr-eng
papermerge       | 2021-01-12T08:36:50.575252549Z tesseract-ocr-eng is already the newest version (1:4.00~git30-7274cfa-1).
papermerge       | 2021-01-12T08:36:54.855432077Z package tesseract-ocr-esp" not found in the repository, skipping
```

My docker-compose.yaml looks like this:

```
papermerge:
    image: ghcr.io/linuxserver/papermerge
    container_name: papermerge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - DOCKER_MODS=linuxserver/mods:papermerge-multilangocr
      - OCRLANG="eng,deu,esp"
    volumes:
      - <omitted>:/config
      - <omitted>:/data
    ports:
      - 8000:8000
    restart: unless-stopped
```

And my papermerge.conf.py:

```
DBUSER = "root"
DBPASS = "root"
DBHOST = "mariadb"
DBNAME = "papermerge"

MEDIA_DIR = "/data/media"
STATIC_DIR = "/app/papermerge/static"
MEDIA_URL = "/media/"
STATIC_URL = "/static/"
IMPORTER_DIR = "/data/import"

OCR_DEFAULT_LANGUAGE = "deu"

OCR_LANGUAGES = {
    "eng": "English",
    "esp": "Spanish",
    "deu": "Deutsch",
}
```

Is this a bug or did I do something wrong?
