### ISSUE TITLE
GeoIP mod: Log full of these warnings

### ISSUE THREAD

**Issue by YouveGotMeowxy** [linuxserver/docker-mods#185]
Is this ok to see in the logs?  If so, is there some way to silence them so they don't keep cluttering the logs?  If not ok, how can I fix it?

Warnings (a bunch of : **WARNING :: Failed to match regex that previously matched!? Skipping this line!**):

https://pastebin.com/X9CaZw38

Here's my nginx.conf:

```
## Version 2020/09/01 - Changelog: https://github.com/linuxserver/docker-swag/commits/master/root/defaults/nginx.conf

user abc;
worker_processes 4;
pid /run/nginx.pid;
include /etc/nginx/modules/*.conf;

events {
	worker_connections 768;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	variables_hash_max_size 2048;
	large_client_header_buffers 4 16k;

	client_max_body_size 0;

	include /etc/nginx/mime.types;
	default_type application/octet-stream;

    log_format geoip2influx '$remote_addr - $remote_user[$time_local]'
           '"$request" $status $body_bytes_sent'
           '"$http_referer" $host "$http_user_agent"'
           '"$request_time" "$upstream_connect_time"'
           '"$geoip2_data_city_name" "$geoip2_data_country_iso_code"';

	##
	# Logging Settings
	##

	access_log /config/log/nginx/access.log geoip2influx;
	error_log /config/log/nginx/error.log;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_disable "msie6";

	##
	# WebSocket proxying
	##
	map $http_upgrade $connection_upgrade {
		default upgrade;
		''      close;
	}

	##
	# Virtual Host Configs
	##
	include /etc/nginx/conf.d/*.conf;
	include /config/nginx/site-confs/*;

	##
	# Geoip2 config
	##
	# Uncomment to add the Geoip2 configs needed to geo block countries/cities.
	##
	include /config/nginx/geoip2.conf;
}

daemon off;

```

here's my compose:

```
  swag:
    image: ghcr.io/linuxserver/swag:latest
    environment:
      - TZ=America/Chicago
      - "URL=domain.rocks"
      - 'SUBDOMAINS=bitwarden,gotify,grafana,nextcloud,mydomain,openhab,plex,prometheus,resilio-sync,sourcegraph,syncthing,wallabag'
      - PUID=1000
      - PGID=1000
      - VALIDATION=dns
      - ONLY_SUBDOMAINS=true
      - DNSPLUGIN=cloudflare
      - "MAXMINDDB_LICENSE_KEY=redacted"
      - DOCKER_MODS=linuxserver/mods:swag-ffmpeg|linuxserver/mods:swag-imagemagick|linuxserver/mods:swag-geoip2influx
      - INFLUX_HOST=influxdb
      - INFLUX_DATABASE=nginx
      - GEOIP2INFLUX_LOG_LEVEL=info
    volumes:
      - /opt/docker/configs/Swag/config:/config:rw
      - /opt/docker/logs/swag:/config/log:rw 
      - /opt/docker/configs/Swag/.bashrc:/root/.bashrc:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9999:443
    deploy:
      mode: global
      restart_policy:
        condition: any
    networks:
      - oc
```
