### ISSUE TITLE
permission denied issues when using Extension Arguments - Docker mod for code-server

### ISSUE THREAD

**Issue by pheetr** [linuxserver/docker-mods#270]
Hi, as the title says, I'm running into permission denied issues when I try to run the code-server container with the Extension Arguments mod. 

In the logs I can see that the mod successfully installed the extension I specified in the docker-compose.
Once I log into code-server though, anything I try to do results in permission denied error messages. This includes trying to change the color scheme or editing the extension's settings.

I am using $PUID and $PGID to set the right user context for code-server.

If I comment out the two lines enabling the mod in the docker-compose.yml everything works fine.

Initially I ran into this on a NAS, but I've also reproduced on standard Ubuntu 20.04.3 LTS with Docker 20.10.10.

Logs:
[mod-init] Attempting to run Docker Modification Logic,
[mod-init] Applying linuxserver/mods:code-server-extension-arguments files to container,
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 01-migrations: executing... ,
[migrations] started,
[migrations] no migrations found,
[cont-init.d] 01-migrations: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
-------------------------------------,
,
To support LSIO projects visit:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1234,
User gid:    1234,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
setting permissions::configuration,
setting permissions::workspace,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] 90-custom-folders: executing... ,
[cont-init.d] 90-custom-folders: exited 0.,
[cont-init.d] 99-custom-scripts: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-scripts: exited 0.,
[cont-init.d] 99-install-extensions: executing... ,
**** installing extension: keesschollaart.vscode-home-assistant ****,
[2021-12-08T18:07:03.587Z] info  Wrote default config file to ~/.config/code-server/config.yaml,
Installing extensions...,
Installing extension 'keesschollaart.vscode-home-assistant'...,
Extension 'keesschollaart.vscode-home-assistant' v1.22.0 was successfully installed.,
[cont-init.d] 99-install-extensions: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
starting with no password,
[services.d] done.,
[2021-12-08T18:07:08.340Z] error parent:370 Uncaught exception: EACCES: permission denied, open '/config/.local/share/code-server/coder-logs/code-server-stdout.log',
[2021-12-08T18:07:08.341Z] error parent:370 Error: EACCES: permission denied, open '/config/.local/share/code-server/coder-logs/code-server-stdout.log',
[2021-12-08T18:07:08.342Z] error parent:370 Uncaught exception: EACCES: permission denied, open '/config/.local/share/code-server/coder-logs/code-server-stderr.log',
[2021-12-08T18:07:08.342Z] error parent:370 Error: EACCES: permission denied, open '/config/.local/share/code-server/coder-logs/code-server-stderr.log',
[2021-12-08T18:07:08.821Z] info  code-server 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2,
[2021-12-08T18:07:08.822Z] info  Using user-data-dir ~/data,
[2021-12-08T18:07:08.838Z] info  Using config file ~/.config/code-server/config.yaml,
[2021-12-08T18:07:08.838Z] info  HTTP server listening on http://0.0.0.0:8443 ,
[2021-12-08T18:07:08.838Z] info    - Authentication is disabled ,
[2021-12-08T18:07:08.839Z] info    - Not serving HTTPS ,
[2021-12-08T18:08:31.564Z] warn  EACCES: permission denied, open '/config/.local/share/code-server/heartbeat',
[2021-12-08T18:08:31.570Z] warn  EACCES: permission denied, open '/config/.local/share/code-server/coder.json',
[2021-12-08T18:08:31.974Z] warn  vscode EACCES: permission denied, mkdir '/config/data/logs/20211208T180831',
[2021-12-08T18:08:31.976Z] warn  vscode EACCES: permission denied, mkdir '/config/data/User/globalStorage',
[2021-12-08T18:08:31.976Z] warn  vscode EACCES: permission denied, mkdir '/config/data/User/workspaceStorage',
rejected promise not handled within 1 second: Error: EACCES: permission denied, mkdir '/config/data/logs/20211208T180831',
stack trace: Error: EACCES: permission denied, mkdir '/config/data/logs/20211208T180831',
[Error: EACCES: permission denied, mkdir '/config/data/logs/20211208T180831'] {,
  errno: -13,,
  code: 'EACCES',,
  syscall: 'mkdir',,
  path: '/config/data/logs/20211208T180831',
},
[2021-12-08T18:08:33.311Z] warn  EACCES: permission denied, open '/config/.local/share/code-server/coder.json',
TypeError: Cannot read property 'publicLogError2' of undefined,
    at w._flushBuffer (/usr/local/share/.config/yarn/global/node_modules/code-server/vendor/modules/code-oss-dev/out/vs/server/entry.js:26:465),
    at Timeout._onTimeout (/usr/local/share/.config/yarn/global/node_modules/code-server/vendor/modules/code-oss-dev/out/vs/server/entry.js:26:345),
    at listOnTimeout (internal/timers.js:557:17),
    at processTimers (internal/timers.js:500:7),
[2021-12-08T18:09:31.565Z] warn  EACCES: permission denied, open '/config/.local/share/code-server/heartbeat'

**Comment by aptalca** [comment]
@RoboMagus
This might be due to the install command running as root. Can you test changing the command to run as `abc`?
`s6-setuidgid abc /usr/local/bin/code-server . . . `

**Comment by RoboMagus** [comment]
@pheetr, 

I'm currently in the process of reproducing your issue but so far have not ran into an access denied error.
Could you please share a snippet of your docker-compose related to your code-server container instance? 
Also to be sure, does the user 1234 own the code-server config directory / does it exist on your host?

Thanks!

**Comment by pheetr** [comment]
Sure, please see my docker compose below.
I'm running this in a single-user ubuntu test environment now, and while the user and group id values posted here are made up, in reality they are the ones belonging to this single user.

This is the first time I've attempted to use the linuxserver mod framework and the reason I'm inclined to think that the issue has something to do with the mod is that I'm only getting these errors when DOCKER_MODS and VSCODE_EXTENSION_IDS variables are set. If I comment out those two lines in the docker-compose file there are no issues. The simplest test I'm doing is switching the color theme in the code-server welcome screen from default to dark. With the mod enabled it won't change to dark and I can see the error message talking about permission issue with config/data/User/settings.json

As far as directory and permissions go, I'm not a linux or permissions expert at all, so I've tried bringing up the container in two ways: 
 - by creating the folders code-server and config before bringing  up the container (the user I'm logged in with is the one referenced in the docker-compose file)
 - letting docker create the entire folder structure

Both options resulted in errors with the mod enabled and no issues with mod disabled.

```
version: "3.5"
services:
  code-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server
    hostname: cs
    networks:
      - net
    ports:
      - 8843:8443
    environment:
      - PUID=1234
      - PGID=1234
      - TZ=Europe/Dublin
      - DOCKER_MODS=linuxserver/mods:code-server-extension-arguments #adding code-server Extension Arguments docker mod
      - VSCODE_EXTENSION_IDS=keesschollaart.vscode-home-assistant #adding https://github.com/keesschollaart81/vscode-home-assistant
      #- PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      #- SUDO_PASSWORD=password #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      #- DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /home/user/Docker/AppData/code-server/config:/config
    restart: unless-stopped    
    logging:
        driver: json-file
        options:
            max-size: "10m"
            max-file: "5"    
networks:
  net:
    external: true
```
