### ISSUE TITLE
code-server error for new docker-mod: No such file or directory unable to exec bash

### ISSUE THREAD

**Issue by Hpmason** [linuxserver/docker-mods#375]
When trying to make a docker mod for code-server, I was trying to test my image, but I keep getting the following error.
```
code-server  | [cont-init.d] 98-rust: executing...
: No such file or directory unable to exec bash
code-server  | [cont-init.d] 98-rust: exited 127.
```
I can't seem to find any noticeable differences between my shell scripts and some of the other code-server docker-mods. Is there an issue with using a personal image and not from the linuxserver repo? 

[Here's the fork](https://github.com/Hpmason/docker-mods/tree/code-server-rust) I'm working on now.

Here's my docker-compose.yml file I'm using
```
---
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment: 
      - PUID=1000
      - GUID=1000
      - TZ=America/New_York
      - DOCKER_MODS=hpmason/code-server-rust:latest
    volumes:
      - ./config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
```
