### ISSUE TITLE
universal-tshoot: fails to start, no such file "run"

### ISSUE THREAD

**Issue by nopoz** [linuxserver/docker-mods#487]
universal-tshoot can't start on boot on a freshly created container - this in-turn prevents the boot of the plex service. If I remove the "linuxserver/mods:universal-tshoot" bit from the compose file, everything starts up as expected. 

Relevant Log Snippet:

```
s6-rc-oneshot-run: fatal: unable to exec /etc/s6-overlay/s6-rc.d/init-mod-tshoot/run: No such file or directory
s6-rc: warning: unable to start service init-mod-universal-tshoot: command exited 127
```

Full Log:

```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/mods:universal-tshoot files to container
[mod-init] linuxserver/mods:universal-tshoot applied to container
[mod-init] Applying linuxserver/mods:universal-cron files to container
[mod-init] linuxserver/mods:universal-cron applied to container
[mod-init] Applying linuxserver/mods:universal-package-install files to container
[mod-init] linuxserver/mods:universal-package-install applied to container
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service 00-legacy: starting
s6-rc: info: service 00-legacy successfully started
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/01-envfile
cont-init: info: /etc/cont-init.d/01-envfile exited 0
cont-init: info: running /etc/cont-init.d/01-migrations
[migrations] started
[migrations] no migrations found
cont-init: info: /etc/cont-init.d/01-migrations exited 0
cont-init: info: running /etc/cont-init.d/02-tamper-check
cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
cont-init: info: running /etc/cont-init.d/10-adduser

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1001
User gid:    1001
-------------------------------------

cont-init: info: /etc/cont-init.d/10-adduser exited 0
cont-init: info: running /etc/cont-init.d/40-chown-files
cont-init: info: /etc/cont-init.d/40-chown-files exited 0
cont-init: info: running /etc/cont-init.d/45-plex-claim
cont-init: info: /etc/cont-init.d/45-plex-claim exited 0
cont-init: info: running /etc/cont-init.d/50-gid-video
**** creating video group videoe82r with id 109 ****
**** adding /dev/dri/renderD128 to video group videoe82r with id 109 ****
**** adding /dev/dri/card0 to video group video with id 44 ****
cont-init: info: /etc/cont-init.d/50-gid-video exited 0
cont-init: info: running /etc/cont-init.d/60-plex-update
Docker is used for versioning skip update check
cont-init: info: /etc/cont-init.d/60-plex-update exited 0
cont-init: info: running /etc/cont-init.d/90-custom-folders
cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
cont-init: info: running /etc/cont-init.d/99-custom-scripts
[custom-init] no custom files found exiting...
cont-init: info: /etc/cont-init.d/99-custom-scripts exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mod-universal-tshoot: starting
s6-rc: info: service init-mod-universal-package-install-add-package: starting
s6-rc: info: service init-mod-universal-cron-add-package: starting
s6-rc-oneshot-run: fatal: unable to exec /etc/s6-overlay/s6-rc.d/init-mod-tshoot/run: No such file or directory
s6-rc: warning: unable to start service init-mod-universal-tshoot: command exited 127
**** Adding cron to package install list ****
**** Adding vim-tiny to install list ****
**** Adding less to install list ****
s6-rc: info: service init-mod-universal-cron-add-package successfully started
s6-rc: info: service init-mod-universal-package-install-add-package successfully started
```

Compose file:

```
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:version-1.28.0.5999-97678ded3
    container_name: plex
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=America/Los_Angeles
      - PUID=1001
      - PGID=1001
      - VERSION=docker
      - DOCKER_MODS=linuxserver/mods:universal-tshoot|linuxserver/mods:universal-cron|linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=vim-tiny|less
    volumes:
      - /var/lib/docker/volumes/plex:/config
      - /mnt/tv:/tv
      - /mnt/movies:/movies
      - /mnt/music:/music
      - /mnt/plex_db:/backup
      - /dev/shm:/transcode_ram
    restart: unless-stopped
```

Docker version 20.10.17, build 100c701
