### ISSUE TITLE
code-server:nodejs

### ISSUE THREAD

**Issue by toxic0berliner** [linuxserver/docker-mods#510]
I am unable to start my codeserver container when enabling the following mod : 
`linuxserver/mods:code-server-nodejs`

The only offending line I find in my logs is the last line here. I added what's above just for completeness...  

```
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
done.
Processing triggers for php8.1-cli (8.1.2-1ubuntu2.5) ...
Processing triggers for libapache2-mod-php8.1 (8.1.2-1ubuntu2.5) ...
Warning: Could not load Apache 2.4 maintainer script helper.
creating npm global folder in /config
setting npm to global folder in /config
ensuring npm-global is in PATH
grep: /etc/services.d/code-server/run: No such file or directory
sed: can't read /etc/services.d/code-server/run: No such file or directory
s6-rc: warning: unable to start service init-mod-code-server-npmglobal-install: command exited 2
```

Here is my compose file for reference : 
<details>
<summary>compose.yml (click to expand)</summary>
```
version: "3"
services:
  codeserver:
    container_name: codeserver
    image: lscr.io/linuxserver/code-server:latest
    hostname: codeserver
    labels:
      traefik.http.services.codeserver.loadbalancer.server.port: 8443
      traefik.http.services.codeserver.loadBalancer.server.scheme: http
      traefik.http.routers.codeserver.rule: Host(`ide.example.com`)
      subdomain: codeserver
    volumes:
      - codeserver-config:/config
      - orion-dev:/data/orion/dev
      - orion-web:/data/orion/web
      - orion-docker:/data/orion/docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1026
      - PGID=100
      - UMASK=002
      - TZ=Europe/Paris
      #- PASSWORD=password #optional
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      #- SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=ide.example.com #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      #- DOCKER_MODS=linuxserver/mods:code-server-docker|linuxserver/mods:code-server-extension-arguments|linuxserver/mods:code-server-shellcheck|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-npmglobal|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-dotnet|linuxserver/mods:code-server-golang|linuxserver/mods:code-server-java11|linuxserver/mods:code-server-php|linuxserver/mods:universal-package-install
      - DOCKER_MODS=linuxserver/mods:code-server-docker|linuxserver/mods:code-server-extension-arguments|linuxserver/mods:code-server-shellcheck|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-npmglobal|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-dotnet|linuxserver/mods:code-server-golang|linuxserver/mods:code-server-java11|linuxserver/mods:code-server-php|linuxserver/mods:universal-package-install
      - VSCODE_EXTENSION_IDS=vscode-icons-team.vscode-icons|ms-azuretools.vscode-docker|donjayamanne.git-extension-pack|mhutchie.git-graph|redhat.ansible
      - INSTALL_PACKAGES=wget|vim|zip|apt-transport-https|ansible|dnsutils|iputils-ping|netcat
      #- "EXTENSIONS_GALLERY=\"extensionsGallery\": {\"serviceUrl\": \"https://marketplace.visualstudio.com/_apis/public/gallery\",\"cacheUrl\": \"https://vscode.blob.core.windows.net/gallery/index\",\"itemUrl\": \"https://marketplace.visualstudio.com/items\"}"
      - GITLAB_WORKFLOW_INSTANCE_URL=${GITLAB_INSTANCE}
      - GITLAB_WORKFLOW_TOKEN=${GITLAB_TOKEN}
      - VISUAL=vim
      - EDITOR="$VISUAL"
    restart: unless-stopped
    networks:
      traefiknet:
        aliases: 
          - codeserver
volumes:
  codeserver-config:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_VOLUMES}/${STACKNAME}/codeserver/config
  orion-dev:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_ORION}/dev/
  orion-web:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_ORION}/web
  orion-docker:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_ORION}/docker
networks:
  traefiknet:
    name: traefiknet
    driver: bridge
    external: true

```
</details>

Using the same compose file but removing nodejs from the mods list works just fine for me.
