### ISSUE TITLE
Error: nginx: [emerg] unknown "geoip2_data_country_iso_code" variable when configuring Swag-Maxmind mod

### ISSUE THREAD

**Issue by Sundur94** [linuxserver/docker-mods#562]
I was following the documentation here on Github aswell as the following guide https://virtualize.link/secure/ under Geoblock.

After configuring everything i get this error "nginx: [emerg] unknown "geoip2_data_country_iso_code" variable"
This is referenced in the /config/nginx/maxmind.conf file. Which looks like this:

```
map $geoip2_data_country_iso_code $geo-blacklist {
    default yes;
    CN no; #China
    RU no; #Russia
    HK no; #Hong Kong
    IN no; #India
    IR no; #Iran
    VN no; #Vietnam
    TR no; #Turkey
    EG no; #Egypt
    MX no; #Mexico
    JP no; #Japan
    KR no; #South Korea
    KP no; #North Korea
    PE no; #Peru
    BR no; #Brazil
    UA no; #Ukraine
    ID no; #Indonesia
    TH no; #Thailand
    US no; #USA
}
```

I am currently only testing this on my vaultwarden.subdomain.conf and i added the following:
` if ($geo-blacklist = no) { return 404; } `

I also added the following to /config/nginx/nginx.conf under "http"

```
  # Geoip filter
  include /config/nginx/maxmind.conf;
```

When i get the error my other mod "nginx-dashboard" stops working aswell.

The GeoLite2-City.mmdb file gets downloaded to /config/geoip2db/

Am i doing something wrong?

My docker-compose:

```
version: "3.8"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/London
      - URL=xxxxxxx
      - VALIDATION=http
      - SUBDOMAINS=req,bw,cloud #optional
#      - CERTPROVIDER= #optional
#      - DNSPLUGIN=cloudflare #optional
#      - PROPAGATION= #optional
      - EMAIL= xxxxxx
      - ONLY_SUBDOMAINS=true #optional
#      - EXTRA_DOMAINS= #optional
#      - STAGING=false #optional
      - DOCKER_MODS=linuxserver/mods:swag-dashboard|linuxserver/mods:swag-maxmind
      - MAXMINDDB_LICENSE_KEY=xxxxxxxxx
    volumes:
      - /docker/appdata/swag:/config
    ports:
      - 1880:80
      - 18443:443
      - 8754:81
    restart: unless-stopped
```

System:
Ubuntu 20.04.5 LTS
Docker 20.10.22, build 3a2c30b

The docker-log from my SWAG:

```
Using Let's Encrypt as the cert provider
SUBDOMAINS entered, processing
SUBDOMAINS entered, processing
Only subdomains, no URL in cert
Sub-domains processed are:  -d xxxxxxxx -d xxxxxxx -d xxxxxxxxxx
E-mail address entered:  xxxxxxxxxxxxx
http validation is selected
Certificate exists; parameters unchanged; starting nginx
cont-init: info: /etc/cont-init.d/50-certbot exited 0
cont-init: info: running /etc/cont-init.d/55-permissions
cont-init: info: /etc/cont-init.d/55-permissions exited 0
cont-init: info: running /etc/cont-init.d/60-renew
The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
cont-init: info: /etc/cont-init.d/60-renew exited 0
cont-init: info: running /etc/cont-init.d/70-outdated
cont-init: info: /etc/cont-init.d/70-outdated exited 0
cont-init: info: running /etc/cont-init.d/85-version-checks
cont-init: info: /etc/cont-init.d/85-version-checks exited 0
cont-init: info: running /etc/cont-init.d/99-custom-files
[custom-init] No custom files found, skipping...
cont-init: info: /etc/cont-init.d/99-custom-files exited 0
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-mods: starting
s6-rc: info: service init-mods successfully started
s6-rc: info: service init-mod-swag-maxmind-add-package: starting
s6-rc: info: service init-mod-swag-dashboard-add-package: starting
**** Applying the SWAG dashboard mod... ****
**** Installing/updating goaccess ****
**** libmaxminddb already installed, skipping ****
s6-rc: info: service init-mod-swag-maxmind-add-package successfully started
**** libmaxminddb already installed, skipping ****
**** Applied the SWAG dashboard mod ****
s6-rc: info: service init-mod-swag-dashboard-add-package successfully started
s6-rc: info: service init-mods-package-install: starting
s6-rc: info: service init-mods-package-install successfully started
s6-rc: info: service init-mod-swag-maxmind-setup: starting
Applying the maxmind mod...
Applied the maxmind mod
s6-rc: info: service init-mod-swag-maxmind-setup successfully started
s6-rc: info: service init-mods-end: starting
s6-rc: info: service init-mods-end successfully started
s6-rc: info: service init-services: starting
s6-rc: info: service init-services successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun cron (no readiness notification)
services-up: info: copying legacy longrun fail2ban (no readiness notification)
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
s6-rc: info: service legacy-services successfully started
s6-rc: info: service 99-ci-service-check: starting
[ls.io-init] done.
s6-rc: info: service 99-ci-service-check successfully started
nginx: [emerg] unknown "geoip2_data_country_iso_code" variable
Server ready
nginx: [emerg] unknown "geoip2_data_country_iso_code" variable

```
