### ISSUE TITLE
code-server-golang: Go in not in PATH

### ISSUE THREAD

**Issue by 0xERR0R** [linuxserver/docker-mods#598]
Steps to reproduce:

- Start code-server with golang mod with following docker-compose.yaml
  ```yaml
  version: "2.1"
  services:
    code-server:
      image: lscr.io/linuxserver/code-server:latest
      environment:
        - DOCKER_MODS=linuxserver/mods:code-server-golang
      ports:
        - 8443:8443
  ```

- Open Running code-server in browser: (http://localhost:8443/)
- Start new Terminal
- Type `go version`

Expected output: actual Go version
Actual output: `bash: go: command not found`

Go binary is not in path:

```bash
abc@fa43cb77066c:~/workspace$ echo $PATH
/app/code-server/lib/vscode/bin/remote-cli:/command:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

But Go is installed in `/usr/local/go/bin` and can be executed

```bash
abc@fa43cb77066c:~/workspace$ /usr/local/go/bin/go version
go version go1.20.2 linux/amd64
```

I see also following docker container output:

```
code-server_1  | **** ensuring golang is in PATH ****
code-server_1  | **** Installing golang ****
```
