### ISSUE TITLE
universal-calibre not install

### ISSUE THREAD

**Issue by vampywiz17** [linuxserver/docker-mods#729]
Hello there,

Here my docker-compose:

```
version: "3"
services:
  calibre-web:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1005
      - TZ=$TZ
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
    volumes:
      - $APPDATA_PATH/calibre-web/config:/config
      - $APPDATA_PATH/calibre-web/provider:/app/calibre-web/cps/metadata_provider
      - /mnt/adat/Torrent/Books:/mnt/adat/Torrent/Books
      - /mnt/adat/Torrent/Books_calibre-web:/books
    ports:
      - 8083:8083
    restart: unless-stopped
```

i re-create container today, but after the universal-calibre not installed. I see this in log:

```
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-calibre to container
[mod-init] linuxserver/mods:universal-calibre could not be found on lscr.io
[migrations] started
[migrations] no migrations found
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1005
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

seems it search it a wrong place....
