### ISSUE TITLE
universal-cron not working with code-server image

### ISSUE THREAD

**Issue by jmbannon** [linuxserver/docker-mods#782]
```
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DOCKER_MODS=linuxserver/mods:universal-cron
    volumes:
      - ./volumes/code-server:/config
    ports:
      - 8444:8443
    restart: unless-stopped
```

```
code-server     | [mod-init] Attempting to run Docker Modification Logic
code-server     | [mod-init] Adding linuxserver/mods:universal-cron to container
code-server     | [mod-init] Downloading linuxserver/mods:universal-cron from lscr.io
code-server     | [mod-init] Installing linuxserver/mods:universal-cron
code-server     | [mod-init] linuxserver/mods:universal-cron applied to container
code-server     | [migrations] started
code-server     | [migrations] no migrations found
code-server     | ───────────────────────────────────────
code-server     | 
code-server     |       ██╗     ███████╗██╗ ██████╗ 
code-server     |       ██║     ██╔════╝██║██╔═══██╗
code-server     |       ██║     ███████╗██║██║   ██║
code-server     |       ██║     ╚════██║██║██║   ██║
code-server     |       ███████╗███████║██║╚██████╔╝
code-server     |       ╚══════╝╚══════╝╚═╝ ╚═════╝ 
code-server     | 
code-server     |    Brought to you by linuxserver.io
code-server     | ───────────────────────────────────────
code-server     | 
code-server     | To support LSIO projects visit:
code-server     | https://www.linuxserver.io/donate/
code-server     | 
code-server     | ───────────────────────────────────────
code-server     | GID/UID
code-server     | ───────────────────────────────────────
code-server     | 
code-server     | User UID:    1000
code-server     | User GID:    1000
code-server     | ───────────────────────────────────────
code-server     | 
code-server     | /etc/s6-overlay/s6-rc.d/init-mod-universal-crontab-config/run: line 29: crontab: command not found
code-server     | /etc/s6-overlay/s6-rc.d/init-mod-universal-crontab-config/run: line 29: crontab: command not found
code-server     | s6-rc: warning: unable to start service init-mod-universal-crontab-config: command exited 127
```
