### ISSUE TITLE
Cant set other folder for swag-auto-reload

### ISSUE THREAD

**Issue by VergilGao** [linuxserver/docker-mods#795]
here is my docker-compose file:
```
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - DOCKER_MODS=linuxserver/mods:swag-auto-reload
      - WATCHLIST="/config/keys/"
    volumes:
      - /root/app/data/nginx:/config
      - /root/certs:/config/keys
    restart: unless-stopped
```
and when i run this docker container, it shows:
```
$ docker logs nginx | tail -f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
(1/2) Installing inotify-tools-libs (3.22.6.0-r2)
(2/2) Installing inotify-tools (3.22.6.0-r2)
Executing busybox-1.36.1-r5.trigger
OK: 144 MiB in 181 packages
[custom-init] No custom files found, skipping...
MOD Auto-reload: Watching the following files/folders for changes (excluding .sample and .md files):
/config/nginx
[ls.io-init] done.
```
it doesnt work with my option `WATCHLIST="/config/keys/"`

then i test the WATCHLIST in container:
```
$ docker exec -it nginx /bin/sh
root@6e47e12ee25c:/# echo $WATCHLIST
"/config/keys/|/config/nginx/site-conf"
```
it seems hanppened for at least 3 month because when i open my web site it shows my cert expire yesterday.
