### ISSUE TITLE
swag-crowdsec missing dependency nginx-mod-http-lua

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [linuxserver/docker-mods#798]
`- DOCKER_MODS=linuxserver/mods:swag-crowdsec`

resulted into error:
nginx: [emerg] unknown directive "lua_package_path" in /etc/nginx/http.d/crowdsec_nginx.conf:1

`lua_package_path` is only valid config option while ngx_http_lua_module.so is loaded. But it does not exist by default and missing /etc/nginx/modules/30_http_lua.conf which should load it.
```yaml

  swag: # Secure Web Application Gateway
    image: lscr.io/linuxserver/swag
    environment:
    - DOCKER_MODS=linuxserver/mods:swag-crowdsec
    # workaround for (Error loading shared library /var/lib/nginx/modules/ngx_http_lua_module.so: No such file or directory)
    - INSTALL_PACKAGES=nginx-mod-http-lua
```
