### ISSUE TITLE
[Error] flac2mp3.sh: Error|/usr/bin/ffmpeg is required by this script

### ISSUE THREAD

**Issue by Uuugh** [linuxserver/docker-mods#813]
Upon adding the script via Lidarr "Add Connection - Custom Script" I receive the following error
`[Error] flac2mp3.sh: Error|/usr/bin/ffmpeg is required by this script`

It is resolved by entering the Lidarr console and running 
`apk add ffmpeg`

I'd suggested either incorporating it in either lidarr-flac2mp3, flac2mp3.sh, or the installation instructions.

Thanks!

My (editted for length) docker compose file:
```
version: '3.3'
services:
  gluetun:
    image: qmcgaw/gluetun
...	
      - 8686:8686		# Lidarr Music
...
lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    depends_on:
      gluetun:
        condition: service_healthy
    network_mode: service:gluetun
    environment:
      - PUID=1030
      - PGID=100
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/mods:lidarr-flac2mp3 # https://github.com/linuxserver/docker-mods/tree/lidarr-flac2mp3
    volumes:
      - /mnt/docker/config/lidarr:/config
      - /mnt/docker/data:/data
      #- /mnt/DSMLUN/config/lidarr:/config
      - /mnt/DSMLUN/data:/data/DSMLUN
      - /mnt/media:/data/NAS
    restart: always
```
