### ISSUE TITLE
Incorrect sudo password

### ISSUE THREAD

**Issue by tholeb** [linuxserver/docker-mods#816]
I can't sudo while in the container, the password is always incorrect, even though in the logs there is : 
```
setting up sudo access
adding abc to sudoers
```

I checked the sudoers list, and the abc user is not present (`grep -Po '^sudo.+:\K.*$' /etc/group`).

I use ansible to create the container : 
```yaml
- name: VSCode - Run container using podman
  containers.podman.podman_container:
    name: vscode
    image: linuxserver/code-server:latest
    state: started
    recreate: true
    volume:
      - vscode-storage:/workspace
      - vscode-config:/config
    restart_policy: on-failure
    ports:
      - 1029:8443
    env:
      PUID: 1000
      PGID: 1003
      TZ: Europe/Paris
      HASHED_PASSWORD: "{{ vscode_password_hash.stdout }}"
      SUDO_PASSWORD_HASH: "{{ sudo_password_hash.stdout }}"
      DEFAULT_WORKSPACE: /workspace
    generate_systemd:
      path: /etc/systemd/system
      new: true
      time: 120
  notify:
    - Systemd daemon reload
    - Restart vscode
```

1000:1003 is a user from my raspberry, I run the playbook with `become: root`
