### ISSUE TITLE
Kasm with docker-in-docker mod is failing to start

### ISSUE THREAD

**Issue by ssaid** [linuxserver/docker-mods#831]
Hi! I want the containers inside the kasm to have the capability of spinning up new containers, so i want to enable docker inside them.
Is this the correct approach? Or if not, can you provide me a path in doing so ? Thanks!

This is my compose.yml
```yaml
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=443
      - PUID=1001
      - PGID=1001
      - DOCKER_MODS=linuxserver/mods:universal-docker-in-docker
    volumes:
      - ./data:/opt
      - ./profiles:/profiles #optional
    ports:
      - 3000:3000
       - 443:443
    restart: unless-stopped
```
Pretty much as standard, but this outputs an error...
```bash
kasm  | [custom-init] No custom files found, skipping...
kasm  | sed: couldn't flush stdout: Device or resource busy
kasm  | failed to start daemon, ensure docker is not running or delete /var/run/docker.pid: process with PID 676 is still running
kasm  | **** Enabling QEMU ****
kasm  | failed to start containerd: timeout waiting for containerd to start
kasm  | docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
kasm  | See 'docker run --help'.
kasm  | s6-rc: warning: unable to start service init-mod-universal-docker-in-docker-qemu: command exited 125
kasm  | failed to start containerd: timeout waiting for containerd to start
```
