### ISSUE TITLE
universal-stdout-logs No such file or directory

### ISSUE THREAD

**Issue by tetebueno** [linuxserver/docker-mods#832]
Can't make `universal-stdout-logs` mod work on qBittorrent (`lscr.io/linuxserver/qbittorrent:4.6.3`). I get the following log when starting the container:

```
[mod-init] Running Docker Modification Logic
[mod-init] Adding linuxserver/mods:universal-stdout-logs to container
[mod-init] linuxserver/mods:universal-stdout-logs at sha256:a7c47f8676ef30e2d1b0f04b02a719d2dcb7c8b968460650f3ef42db2f7ef215 has been previously applied skipping
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
[custom-init] No custom files found, skipping...
Executing: tail -F "/config/qBittorrent/logs/qbittorrent.log"
tail: cannot open '"/config/qBittorrent/logs/qbittorrent.log"' for reading: No such file or directory
WebUI will be started shortly after internal preparations. Please wait...
******** Information ********
To control qBittorrent, access the WebUI at: http://localhost:9092
Connection to localhost (127.0.0.1) 9092 port [tcp/*] succeeded!
[ls.io-init] done.
```

Log file is there and permissions seem to be OK for the configured user both in the host and in the container.

Here's a `docker-compose.yaml` file to test:

```yaml
version: "3.8"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.3
    container_name: qbittorrent
    restart: unless-stopped
    volumes:
      - /tmp/qbittorrent/config:/config
      - /tmp/qbittorrent/data:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=9091
      - DOCKER_MODS=linuxserver/mods:universal-stdout-logs
      - LOGS_TO_STDOUT="/config/qBittorrent/logs/qbittorrent.log"
    ports:
      - 9091:9091
      - 6881:6881
      - 6881:6881/udp
```
