### ISSUE TITLE
[FEAT] Use K8s 1.31 Image Volume Sources for mods

### ISSUE THREAD

**Issue by yoadey** [linuxserver/docker-mods#956]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

All of them

### Wanted change

In K8s 1.31 a volume Source "image" has been introduce, which uses a OCI based image as a volume, see https://kubernetes.io/blog/2024/08/16/kubernetes-1-31-image-volume-source/
This could be added as an alternative to the current process of downloading the mods each time the container is started, which might also prevent firewall issues in a corporate network. As this is a Kubernetes feature it should probably added as an alternative and not a replacement, since this would not work in Docker/other environments.

I don't know exactly, but maybe it's already somehow possible to do since the mods are already images in an OCI registry? But I don't know how/where they should be mounted, or should they be added in the custom scripts folder?

### Reason for change

Mods download might be blocked by corporate firewalls, prevent multiple downloads of same artifacts, especially if it is started multiple times.

**Comment by Roxedus** [comment]
The mods realistically uses / as its mount point, so it is not feasible with the current design of mods, as volumes doesn't merge contents.

**Comment by yoadey** [comment]
Wouldn't it be possible to mount it to a specific path and then copy everything from there to root, same way current mods are copied? Just the source of the mod files would need to change

**Comment by thespad** [comment]
Possibly. The problem is I don't have any way of testing this at the moment and as we don't support k8s it's hard to justify the time to work on it.

That said I have an idea that might allow it to be done fairly simply, and if I get a chance I'll look into it, but no promises.

**Comment by thespad** [comment]
@yoadey if you fancy testing this, you'll need to mount https://github.com/linuxserver/docker-mods/blob/mod-scripts-sideload-dir/docker-mods.v3 as `/docker-mods` in your container, and then mount your docker mod image at `/mods/<mod base name>`

Then set `DOCKER_MODS_SIDELOAD=true` and set `DOCKER_MODS` to the base name of the mod.

e.g.
```
DOCKER_MODS_SIDELOAD=true 
DOCKER_MODS=universal-tshoot
...
      volumeMounts:
        - name: my-volume
          mountPath: /mods/universal-tshoot
  volumes:
    - name: my-volume
      image:
        reference: lscr.io/linuxserver/mods:universal-tshoot
```

In my local tests it works, but I'm fudging the mount because I'm not running k8s so it may not work in reality.
