### ISSUE TITLE
[FEAT] <title>

### ISSUE THREAD

**Issue by Abruccii** [linuxserver/docker-mods#967]
### Is this a new feature request?

- [X] I have searched the existing issues

### Name of mod

plex-rclone

### Wanted change

Please add branch plex-rclone

### Reason for change

Add Rclone Mod for Plex (and maybe jellyfin?) so that rclone mount can be used to utilize onedrive and other cloud storages as mount for mediafiles

### Proposed code change

https://github.com/Abruccii/docker-mods/tree/plex-rclone

**Comment by aptalca** [comment]
If it's just installing a single repo package, there is no need for a new mod. You can use the universal package install mod: 
https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by thespad** [comment]
If you need a service or additional logic then you'd have to look at a full mod. If you just need to run a one-off command then a custom init script will suffice: https://www.linuxserver.io/custom

**Comment by Abruccii** [comment]
> If you need a service or additional logic then you'd have to look at a full mod. If you just need to run a one-off command then a custom init script will suffice: https://www.linuxserver.io/custom

adding a file "Onedrive" to the custom-services folder according to the documentation you linked (i just changed the memcached command to rclone mount command) im getting the error
`
exec: fatal: unable to exec bash
: No such file or directory
`

```
plex:
    image: linuxserver/plex
    container_name: plex
    runtime: nvidia
    environment:
      - TZ=Europe/Berlin
      - VERSION=docker
      - PUID=0
      - PGID=0
      #- PLEX_CLAIM=claim-h2W3jQesYzkmqN5bf7d1
      - NVIDIA_VISIBLE_DEVICES=all
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=rclone|fuse
    volumes:
      - C:\Plex\config:/config
      - C:\Plex\custom-services:/custom-services.d
    devices:
      - /dev/fuse
    privileged: true
    network_mode: service:wireguard
    restart: unless-stopped
```

```
#!/usr/bin/with-contenv bash

exec rclone mount --config=/config/rclone.conf --allow-other --no-modtime --stats=0 --dir-cache-time=120m --vfs-cache-mode full --user-agent "ISV|rclone.org|rclone/v1.62.2" --onedrive-no-versions --cache-info-age=60m Onedrive:/ /media
```
